### ISSUE TITLE
Remove boost requirement?

### ISSUE THREAD

**Issue by ghost** [SeismicData/asdf-library#21]
I think I will remove the boost requirement since it is only really used for the parser that is not currently needed. This should make installation somewhat simpler. Let me know if you don't think this is a good idea.

**Comment by mpbl** [comment]
Hi,  James,

That's a good idea. Can you tag this version before so we can find it easily if we want to move some of the features to a peripheral package later on?

**Comment by ghost** [comment]
Sure, I tagged this version as v1.0.0
